
"""


'sss_num_unassociated_hits',
'sss_num_unassociated_hits_below_threshold',
'sss_num_associated_hits',
'sss_num_candidates',
'sss_candidate_veto_score',
'sss_candidate_in_nu_slice',
'sss_candidate_num_hits',
'sss_candidate_num_wires',
'sss_candidate_num_ticks',
'sss_candidate_plane',
'sss_candidate_PCA',
'sss_candidate_mean_ADC',
'sss_candidate_ADC_RMS',
'sss_candidate_impact_parameter',
'sss_candidate_fit_slope',
'sss_candidate_fit_constant',
'sss_candidate_mean_tick',
'sss_candidate_max_tick',
'sss_candidate_min_tick',
'sss_candidate_mean_wire',
'sss_candidate_max_wire',
'sss_candidate_min_wire',
'sss_candidate_min_dist',
'sss_candidate_wire_tick_based_length',
'sss_candidate_energy',
'sss_candidate_angle_to_shower',
'sss_candidate_closest_neighbour',
'sss_candidate_remerge',
'sss_candidate_matched',
'sss_candidate_pdg',
'sss_candidate_parent_pdg',
'sss_candidate_trackid',
'sss_candidate_true_energy',
'sss_candidate_overlay_fraction',
'sss_candidate_matched_energy_fraction_best_plane',
'sss3d_ioc_ranked_en',
'sss3d_ioc_ranked_conv',
'sss3d_ioc_ranked_invar',
'sss3d_ioc_ranked_implied_invar',
'sss3d_ioc_ranked_ioc',
'sss3d_ioc_ranked_opang',
'sss3d_ioc_ranked_implied_opang',
'sss3d_ioc_ranked_id',
'sss3d_invar_ranked_en',
'sss3d_invar_ranked_conv',
'sss3d_invar_ranked_invar',
'sss3d_invar_ranked_implied_invar',
'sss3d_invar_ranked_ioc',
'sss3d_invar_ranked_opang',
'sss3d_invar_ranked_implied_opang',
'sss3d_invar_ranked_id',
'sss2d_ioc_ranked_en',
'sss2d_ioc_ranked_conv',
'sss2d_ioc_ranked_ioc',
'sss2d_ioc_ranked_pca',
'sss2d_ioc_ranked_invar',
'sss2d_ioc_ranked_angle_to_shower',
'sss2d_ioc_ranked_num_planes',
'sss2d_invar_ranked_en',
'sss2d_invar_ranked_conv',
'sss2d_invar_ranked_ioc',
'sss2d_invar_ranked_pca',
'sss2d_invar_ranked_invar',
'sss2d_invar_ranked_angle_to_shower',
'sss2d_invar_ranked_num_planes',
'sss2d_conv_ranked_en',
'sss2d_conv_ranked_conv',
'sss2d_conv_ranked_ioc',
'sss2d_conv_ranked_pca',
'sss2d_conv_ranked_invar',
'sss2d_conv_ranked_angle_to_shower',
'sss2d_conv_ranked_num_planes',
'sss3d_num_showers',
'sss3d_shower_start_x',
'sss3d_shower_start_y',
'sss3d_shower_start_z',
'sss3d_shower_dir_x',
'sss3d_shower_dir_y',
'sss3d_shower_dir_z',
'sss3d_shower_length',
'sss3d_shower_conversion_dist',
'sss3d_shower_invariant_mass',
'sss3d_shower_implied_invariant_mass',
'sss3d_shower_impact_parameter',
'sss3d_shower_ioc_ratio',
'sss3d_shower_energy_max',
'sss3d_shower_score',

'trackstub_num_unassociated_hits',
'trackstub_unassociated_hits_below_threshold',
'trackstub_associated_hits',
'trackstub_num_candidates',
'trackstub_candidate_in_nu_slice',
'trackstub_candidate_num_hits',
'trackstub_candidate_num_wires',
'trackstub_candidate_num_ticks',
'trackstub_candidate_plane',
'trackstub_candidate_PCA',
'trackstub_candidate_mean_ADC',
'trackstub_candidate_ADC_RMS',
'trackstub_candidate_veto_score',
'trackstub_candidate_mean_tick',
'trackstub_candidate_max_tick',
'trackstub_candidate_min_tick',
'trackstub_candidate_min_wire',
'trackstub_candidate_max_wire',
'trackstub_candidate_mean_wire',
'trackstub_candidate_min_dist',
'trackstub_candidate_min_impact_parameter_to_shower',
'trackstub_candidate_min_conversion_dist_to_shower_start',
'trackstub_candidate_min_ioc_to_shower_start',
'trackstub_candidate_ioc_based_length',
'trackstub_candidate_wire_tick_based_length',
'trackstub_candidate_mean_ADC_first_half',
'trackstub_candidate_mean_ADC_second_half',
'trackstub_candidate_mean_ADC_first_to_second_ratio',
'trackstub_candidate_track_angle_wrt_shower_direction',
'trackstub_candidate_linear_fit_chi2',
'trackstub_candidate_energy',
'trackstub_candidate_remerge',
'trackstub_candidate_matched',
'trackstub_candidate_matched_energy_fraction_best_plane',
'trackstub_candidate_pdg',
'trackstub_candidate_parent_pdg',
'trackstub_candidate_trackid',
'trackstub_candidate_true_energy',
'trackstub_candidate_overlay_fraction',
'trackstub_num_candidate_groups',
'grouped_trackstub_candidate_indices',
'trackstub_candidate_group_timeoverlap_fraction',
"""


glee_CRT_variables = [
    "CRT_dt",
    "CRT_hits_PE", # vector
    "CRT_hits_time", # vector
    "CRT_hits_x", # vector
    "CRT_hits_y", # vector
    "CRT_hits_z", # vector
    "CRT_min_hit_PE",
    "CRT_min_hit_time",
    "CRT_min_hit_x",
    "CRT_min_hit_y",
    "CRT_min_hit_z",
    "CRT_veto_hit_PE", # vector
    "CRT_veto_nhits",
]

glee_scalar_vars = [
    "reco_asso_showers",
    "reco_asso_tracks",
    "reco_slice_num",
    "reco_slice_objects",
    "reco_slice_shower_num_matched_signal",
    "reco_slice_track_num_matched_signal",
    "reco_vertex_dist_to_SCB",
    "reco_vertex_dist_to_active_TPC",
    "reco_vertex_in_SCB",
    "reco_vertex_size",

    "sss2d_conv_ranked_angle_to_shower",
    "sss2d_conv_ranked_conv",
    "sss2d_conv_ranked_en",
    "sss2d_conv_ranked_invar",
    "sss2d_conv_ranked_ioc",
    "sss2d_conv_ranked_num_planes",
    "sss2d_conv_ranked_pca",
    "sss2d_invar_ranked_angle_to_shower",
    "sss2d_invar_ranked_conv",
    "sss2d_invar_ranked_en",
    "sss2d_invar_ranked_invar",
    "sss2d_invar_ranked_ioc",
    "sss2d_invar_ranked_num_planes",
    "sss2d_invar_ranked_pca",
    "sss2d_ioc_ranked_angle_to_shower",
    "sss2d_ioc_ranked_conv",
    "sss2d_ioc_ranked_en",
    "sss2d_ioc_ranked_invar",
    "sss2d_ioc_ranked_ioc",
    "sss2d_ioc_ranked_num_planes",
    "sss2d_ioc_ranked_pca",
    "sss3d_invar_ranked_conv",
    "sss3d_invar_ranked_en",
    "sss3d_invar_ranked_id",
    "sss3d_invar_ranked_implied_invar",
    "sss3d_invar_ranked_implied_opang",
    "sss3d_invar_ranked_invar",
    "sss3d_invar_ranked_ioc",
    "sss3d_invar_ranked_opang",
    "sss3d_ioc_ranked_conv",
    "sss3d_ioc_ranked_en",
    "sss3d_ioc_ranked_id",
    "sss3d_ioc_ranked_implied_invar",
    "sss3d_ioc_ranked_implied_opang",
    "sss3d_ioc_ranked_invar",
    "sss3d_ioc_ranked_ioc",
    "sss3d_ioc_ranked_opang",
    "sss3d_num_showers",
    "sss_num_associated_hits",
    "sss_num_candidates",
    "sss_num_unassociated_hits",
    "sss_num_unassociated_hits_below_threshold",

    "trackstub_associated_hits",
    "trackstub_num_candidate_groups",
    "trackstub_num_candidates",
    "trackstub_num_unassociated_hits",
    "trackstub_unassociated_hits_below_threshold",
]

# TODO: determine if we should also have trackstub and second shower veto variables here with some type of postprocessing
glee_vector_vars = [
    "isolation_min_dist_trk_shr",
    "isolation_min_dist_trk_unassoc",
    "isolation_nearest_shr_hit_to_trk_time",
    "isolation_nearest_shr_hit_to_trk_wire",
    "isolation_nearest_unassoc_hit_to_trk_time",
    "isolation_nearest_unassoc_hit_to_trk_wire",
    "isolation_num_shr_hits_win_10cm_trk",
    "isolation_num_shr_hits_win_1cm_trk",
    "isolation_num_shr_hits_win_2cm_trk",
    "isolation_num_shr_hits_win_5cm_trk",
    "isolation_num_unassoc_hits_win_10cm_trk",
    "isolation_num_unassoc_hits_win_1cm_trk",
    "isolation_num_unassoc_hits_win_2cm_trk",
    "isolation_num_unassoc_hits_win_5cm_trk",
]

glee_postprocessing_vars = [
    "glee_min_isolation_min_dist_trk_shr",
    "glee_min_isolation_min_dist_trk_unassoc",
    "glee_min_isolation_nearest_shr_hit_to_trk_time",
    "glee_min_isolation_nearest_shr_hit_to_trk_wire",
    "glee_min_isolation_nearest_unassoc_hit_to_trk_time",
    "glee_min_isolation_nearest_unassoc_hit_to_trk_wire",
    "glee_sum_isolation_num_shr_hits_win_10cm_trk",
    "glee_sum_isolation_num_shr_hits_win_1cm_trk",
    "glee_sum_isolation_num_shr_hits_win_2cm_trk",
    "glee_sum_isolation_num_shr_hits_win_5cm_trk",
    "glee_sum_isolation_num_unassoc_hits_win_10cm_trk",
    "glee_sum_isolation_num_unassoc_hits_win_1cm_trk",
    "glee_sum_isolation_num_unassoc_hits_win_2cm_trk",
    "glee_sum_isolation_num_unassoc_hits_win_5cm_trk",
]

glee_training_vars = ["glee_" + var for var in glee_scalar_vars] + glee_postprocessing_vars

glee_vars = glee_scalar_vars + glee_vector_vars
