
lantern_vars = [

    "vtxX",
    "vtxY",
    "vtxZ",

    "vtxScore",
    "recoNuE",
    "foundVertex",

    "vtxIsFiducial",
    "vtxContainment",
    "vtxFracHitsOnCosmic",

    "nShowers",
    "showerIsSecondary",
    "showerPID",
    "showerPhScore",
    "showerElScore",
    "showerMuScore",
    "showerPiScore",
    "showerPrScore",
    "showerCharge",
    "showerPurity",
    "showerComp",
    "showerPrimaryScore",
    "showerFromNeutralScore",
    "showerFromChargedScore",
    "showerCosTheta",
    "showerCosThetaY",
    "showerRecoE",
    "showerDistToVtx",
    "showerStartDirX",
    "showerStartDirY",
    "showerStartDirZ",

    "nTracks",
    "trackIsSecondary",
    "trackClassified",
    "trackCharge",
    "trackComp",
    "trackPurity",
    "trackPrimaryScore",
    "trackFromNeutralScore",
    "trackFromChargedScore",
    "trackCosTheta",
    "trackCosThetaY",
    "trackDistToVtx",
    "trackStartDirX",
    "trackStartDirY",
    "trackStartDirZ",
    "trackElScore",
    "trackPhScore",
    "trackMuScore",
    "trackPiScore",
    "trackPrScore",
    "trackPID",
    "trackRecoE",
]

lantern_direct_training_vars = [
    "lantern_vtxScore",
    "lantern_recoNuE",
    "lantern_foundVertex",
    "lantern_vtxIsFiducial",
    "lantern_vtxContainment",
    "lantern_vtxFracHitsOnCosmic",
]

lantern_postprocessing_training_vars = [
    # shower variables
    "lantern_max_shower_RecoE",
    "lantern_max_electron_shower_RecoE",
    "lantern_max_electron_shower_PhScore",
    "lantern_max_electron_shower_ElScore",
    "lantern_max_electron_shower_MuScore",
    "lantern_max_electron_shower_PiScore",
    "lantern_max_electron_shower_PrScore",
    "lantern_max_electron_shower_electron_confidence",
    "lantern_max_electron_shower_ph_normedscore",
    "lantern_max_electron_shower_el_normedscore",
    "lantern_max_electron_shower_PrimaryScore",
    "lantern_max_electron_shower_FromNeutralScore",
    "lantern_max_electron_shower_FromChargedScore",
    "lantern_max_electron_shower_CosTheta",
    "lantern_max_electron_shower_CosThetaY",
    "lantern_max_electron_shower_DistToVtx",
    "lantern_second_max_electron_shower_RecoE",
    "lantern_second_max_electron_shower_PhScore",
    "lantern_second_max_electron_shower_ElScore",
    "lantern_second_max_electron_shower_MuScore",
    "lantern_second_max_electron_shower_PiScore",
    "lantern_second_max_electron_shower_PrScore",
    "lantern_second_max_electron_shower_electron_confidence",
    "lantern_second_max_electron_shower_ph_normedscore",
    "lantern_second_max_electron_shower_el_normedscore",
    "lantern_second_max_electron_shower_PrimaryScore",
    "lantern_second_max_electron_shower_FromNeutralScore",
    "lantern_second_max_electron_shower_FromChargedScore",
    "lantern_second_max_electron_shower_CosTheta",
    "lantern_second_max_electron_shower_CosThetaY",
    "lantern_second_max_electron_shower_DistToVtx",
    "lantern_max_photon_shower_RecoE",
    "lantern_max_photon_shower_PhScore",
    "lantern_max_photon_shower_ElScore",
    "lantern_max_photon_shower_MuScore",
    "lantern_max_photon_shower_PiScore",
    "lantern_max_photon_shower_PrScore",
    "lantern_max_photon_shower_electron_confidence",
    "lantern_max_photon_shower_ph_normedscore",
    "lantern_max_photon_shower_el_normedscore",
    "lantern_max_photon_shower_PrimaryScore",
    "lantern_max_photon_shower_FromNeutralScore",
    "lantern_max_photon_shower_FromChargedScore",
    "lantern_max_photon_shower_CosTheta",
    "lantern_max_photon_shower_CosThetaY",
    "lantern_max_photon_shower_DistToVtx",
    "lantern_second_max_photon_shower_RecoE",
    "lantern_second_max_photon_shower_PhScore",
    "lantern_second_max_photon_shower_ElScore",
    "lantern_second_max_photon_shower_MuScore",
    "lantern_second_max_photon_shower_PiScore",
    "lantern_second_max_photon_shower_PrScore",
    "lantern_second_max_photon_shower_electron_confidence",
    "lantern_second_max_photon_shower_ph_normedscore",
    "lantern_second_max_photon_shower_el_normedscore",
    "lantern_second_max_photon_shower_PrimaryScore",
    "lantern_second_max_photon_shower_FromNeutralScore",
    "lantern_second_max_photon_shower_FromChargedScore",
    "lantern_second_max_photon_shower_CosTheta",
    "lantern_second_max_photon_shower_CosThetaY",
    "lantern_second_max_photon_shower_DistToVtx",

    # track variables
    "lantern_prim_muon_track_max_muscore",
    "lantern_prim_proton_track_max_prscore",
    "lantern_prim_charged_pion_track_max_piscore",

    # pi0 variables
    "lantern_diphoton_opening_angle",
    "lantern_diphoton_energy",
    "lantern_diphoton_costheta",
    "lantern_diphoton_mass",

    # particle multiplicity variables
    "lantern_prim_shower_photon_num",
    "lantern_prim_shower_electron_num",
    "lantern_prim_shower_muon_num",
    "lantern_prim_shower_charged_pion_num",
    "lantern_prim_shower_proton_num",

    "lantern_prim_track_photon_num",
    "lantern_prim_track_electron_num",
    "lantern_prim_track_muon_num",
    "lantern_prim_track_charged_pion_num",
    "lantern_prim_track_proton_num",

    "lantern_prim_track_photon_num_5MeV",
    "lantern_prim_track_electron_num_5MeV",
    "lantern_prim_track_muon_num_5MeV",
    "lantern_prim_track_charged_pion_num_5MeV",
    "lantern_prim_track_proton_num_5MeV",
    "lantern_prim_track_photon_num_10MeV",
    "lantern_prim_track_electron_num_10MeV",
    "lantern_prim_track_muon_num_10MeV",
    "lantern_prim_track_charged_pion_num_10MeV",
    "lantern_prim_track_proton_num_10MeV",
    "lantern_prim_track_photon_num_15MeV",
    "lantern_prim_track_electron_num_15MeV",
    "lantern_prim_track_muon_num_15MeV",
    "lantern_prim_track_charged_pion_num_15MeV",
    "lantern_prim_track_proton_num_15MeV",
    "lantern_prim_track_photon_num_20MeV",
    "lantern_prim_track_electron_num_20MeV",
    "lantern_prim_track_muon_num_20MeV",
    "lantern_prim_track_charged_pion_num_20MeV",
    "lantern_prim_track_proton_num_20MeV",
    "lantern_prim_track_photon_num_25MeV",
    "lantern_prim_track_electron_num_25MeV",
    "lantern_prim_track_muon_num_25MeV",
    "lantern_prim_track_charged_pion_num_25MeV",
    "lantern_prim_track_proton_num_25MeV",
    "lantern_prim_track_photon_num_30MeV",
    "lantern_prim_track_electron_num_30MeV",
    "lantern_prim_track_muon_num_30MeV",
    "lantern_prim_track_charged_pion_num_30MeV",
    "lantern_prim_track_proton_num_30MeV",
    "lantern_prim_track_photon_num_35MeV",
    "lantern_prim_track_electron_num_35MeV",
    "lantern_prim_track_muon_num_35MeV",
    "lantern_prim_track_charged_pion_num_35MeV",
    "lantern_prim_track_proton_num_35MeV",
    "lantern_prim_track_photon_num_40MeV",
    "lantern_prim_track_electron_num_40MeV",
    "lantern_prim_track_muon_num_40MeV",
    "lantern_prim_track_charged_pion_num_40MeV",
    "lantern_prim_track_proton_num_40MeV",
    "lantern_prim_track_photon_num_45MeV",
    "lantern_prim_track_electron_num_45MeV",
    "lantern_prim_track_muon_num_45MeV",
    "lantern_prim_track_charged_pion_num_45MeV",
    "lantern_prim_track_proton_num_45MeV",
    "lantern_prim_track_photon_num_50MeV",
    "lantern_prim_track_electron_num_50MeV",
    "lantern_prim_track_muon_num_50MeV",
    "lantern_prim_track_charged_pion_num_50MeV",
    "lantern_prim_track_proton_num_50MeV",

    "lantern_prim_photon_num",
    "lantern_prim_electron_num",
    "lantern_prim_muon_num",
    "lantern_prim_charged_pion_num",
    "lantern_prim_proton_num",
]

lantern_training_vars = lantern_direct_training_vars + lantern_postprocessing_training_vars
