
from .pandora_variables import *
from .glee_variables import *
from .lantern_variables import *
from .wc_variables import *

combined_postprocessing_training_vars = [
    "wc_pandora_dist",
    "wc_lantern_dist",
    "lantern_pandora_dist",
]

# variables to throw away after postprocessing in order to make reasonable pandas df sizes
vector_columns = [
    "wc_kine_energy_particle",
    "wc_kine_particle_type",
    "wc_truth_id",
    "wc_truth_pdg",
    "wc_truth_mother",
    "wc_truth_startMomentum",
    "wc_truth_startXYZT",
    "wc_truth_endXYZT",
    "wc_reco_id",
    "wc_reco_pdg",
    "wc_reco_mother",
    "wc_reco_startMomentum",
    "wc_reco_startXYZT",
    "wc_reco_endXYZT",

    "lantern_showerPhScore",

    "blip_x",
    "blip_y",
    "blip_z",
    "blip_dx",
    "blip_dw",
    "blip_energy",
    "blip_true_g4id",
    "blip_true_pdg",
    "blip_true_energy",

    "glee_sss_candidate_veto_score",
    "glee_sss3d_shower_score",

    "lantern_showerIsSecondary",
    "lantern_showerPID",
    "lantern_showerPhScore",
    "lantern_showerElScore",
    "lantern_showerMuScore",
    "lantern_showerPiScore",
    "lantern_showerPrScore",
    "lantern_showerCharge",
    "lantern_showerPurity",
    "lantern_showerComp",
    "lantern_showerPrimaryScore",
    "lantern_showerFromNeutralScore",
    "lantern_showerFromChargedScore",
    "lantern_showerCosTheta",
    "lantern_showerCosThetaY",
    "lantern_showerDistToVtx",
    "lantern_showerStartDirX",
    "lantern_showerStartDirY",
    "lantern_showerStartDirZ",

    "lantern_trackIsSecondary",
    "lantern_trackClassified",
    "lantern_trackCharge",
    "lantern_trackComp",
    "lantern_trackPurity",
    "lantern_trackPrimaryScore",
    "lantern_trackFromNeutralScore",
    "lantern_trackFromChargedScore",
    "lantern_trackCosTheta",
    "lantern_trackCosThetaY",
    "lantern_trackDistToVtx",
    "lantern_trackStartDirX",
    "lantern_trackStartDirY",
    "lantern_trackStartDirZ",
    "lantern_trackElScore",
    "lantern_trackPhScore",
    "lantern_trackMuScore",
    "lantern_trackPiScore",
    "lantern_trackPrScore",
    "lantern_trackPID",

    "lantern_showerRecoE",
    "lantern_trackRecoE",

    "wc_Trecchargeblob_spacepoints_x",
    "wc_Trecchargeblob_spacepoints_y",
    "wc_Trecchargeblob_spacepoints_z",

    "wc_WCPMTInfoPePred",
    "wc_WCPMTInfoPeMeas",
    "wc_WCPMTInfoPeMeasErr",

    "wc_reco_muonMomentum",
    "wc_reco_showerMomentum",
    "wc_truth_muonMomentum",

    "true_gamma_energies",
    "true_gamma_pairconversion_xs",
    "true_gamma_pairconversion_ys",
    "true_gamma_pairconversion_zs",
    "wc_true_gamma_pairconversion_spacepoint_min_distances",

]
vector_columns += [f"pandora_{var}" for var in pandora_vector_vars]
vector_columns += [f"glee_{var}" for var in glee_vector_vars]

combined_training_vars_with_duplicates = wc_training_vars + glee_training_vars + pandora_training_vars + lantern_training_vars + combined_postprocessing_training_vars
# leave blip, nanosecond timing, CRT, spacepoint SSV, and PMT vars for analysis of the selection after the combined BDT for more interpretability

# output from checking_bdt_variables.ipynb
duplicate_bdt_vars = [
    'wc_cosmict_2_filled',
    'wc_cosmict_2_angle_beam',
    'wc_cosmict_3_filled',
    'wc_cosmict_3_flag_inside',
    'wc_cosmict_3_angle_beam',
    'wc_cosmict_3_theta',
    'wc_cosmict_7_angle_beam',
    'wc_cme_energy',
    'wc_cme_length',
    'wc_cme_angle_beam',
    'wc_anc_angle',
    'wc_anc_shower_main_length',
    'wc_anc_shower_total_length',
    'wc_gap_energy',
    'wc_gap_num_valid_tracks',
    'wc_gap_flag_single_shower',
    'wc_lol_3_vtx_n_segs',
    'wc_lol_3_shower_main_length',
    'wc_mgo_energy',
    'wc_mgt_flag_single_shower',
    'wc_mip_quality_energy',
    'wc_br1_1_vtx_n_segs',
    'wc_br1_1_energy',
    'wc_br1_1_n_segs',
    'wc_br1_1_flag_sg_topology',
    'wc_br1_1_flag_sg_trajectory',
    'wc_br1_1_sg_length',
    'wc_br1_2_n_shower_segs',
    'wc_br1_2_shower_length',
    'wc_br1_3_n_shower_main_segs',
    'wc_br3_1_energy',
    'wc_br3_1_n_shower_segments',
    'wc_br3_1_sg_flag_trajectory',
    'wc_br3_1_sg_length',
    'wc_br3_1_total_main_length',
    'wc_br3_1_total_length',
    'wc_br3_4_total_length',
    'wc_br3_8_n_main_segs',
    'wc_br4_1_shower_main_length',
    'wc_br4_1_shower_total_length',
    'wc_br4_1_energy',
    'wc_br4_1_flag_avoid_muon_check',
    'wc_br4_1_n_vtx_segs',
    'wc_br4_1_n_main_segs',
    'wc_stem_dir_flag_single_shower',
    'wc_stem_dir_energy',
    'wc_br2_n_shower_main_segs',
    'wc_br2_sg_length',
    'wc_br2_flag_sg_trajectory',
    'wc_stem_len_energy',
    'wc_brm_shower_total_length',
    'wc_lem_shower_main_length',
    'wc_stw_1_energy',
    'wc_stw_1_dQ_dx',
    'wc_spt_angle_beam_1',
    'wc_spt_angle_drift',
    'wc_vis_1_tmp_length1',
    'glee_reco_asso_showers',
    'glee_reco_slice_num',
    'glee_reco_vertex_size',
    'pandora_shr_tkfit_dedx_U',
    'pandora_shr_tkfit_dedx_V',
    'pandora_shr_tkfit_dedx_Y',
    'pandora_shr_tkfit_nhits_U',
    'pandora_shr_tkfit_nhits_V',
    'pandora_shr_tkfit_nhits_Y',
    'lantern_prim_track_muon_num',
    'lantern_prim_track_proton_num',
    'lantern_prim_track_proton_num_5MeV'
]

combined_training_vars = [var for var in combined_training_vars_with_duplicates if var not in duplicate_bdt_vars]
