"""Compute per-event pi0 Dalitz-decay reweighting weights (Geant4 -> EvtGen).

This module replicates the weight-producing logic of
``ipynb_notebooks/pi0_dalitz_reweighting.ipynb`` so that
``pi0_dalitz_reweighting.parquet`` can be regenerated as part of the main
dataframe-creation pipeline instead of by hand.

Physics.  A pi0 -> e+ e- gamma Dalitz decay at rest has only two dynamical
degrees of freedom: the dilepton invariant mass ``m_ee`` and the lepton helicity
angle ``cos(theta*)``, both invariant under the pi0 lab boost.  Geant4's
``G4DalitzDecayChannel`` samples the lepton angle isotropically (no 1+cos^2 term),
whereas EvtGen's ``PI0_DALITZ`` (Kroll-Wada QED) peaks at the poles.  The entire
Geant4-vs-EvtGen difference is therefore captured by a single 2D weight
``w(m_ee, cos theta*) = rho_EvtGen / rho_Geant4`` built from high-statistics
pure-model samples:
  source = standalone Geant4 (1M, geant4_pi0_dalitz.csv),
  target = EvtGen          (1M, evtgen_pi0_dalitz.csv).
See https://doi.org/10.1103/PhysRevC.95.025202 for the approximate cos(theta*)
analytic prediction.

Two halves:
- ``compute_pi0_dalitz_reweighting`` uses *only* the two pure-model CSV samples to
  build the bin-by-bin weight grid w(m_ee, cos theta*) = EvtGen / Geant4 (a density
  ratio, so <w> = 1 over the Geant4 model by construction), and saves it to
  ``pi0_dalitz_reweighting.parquet`` (one row per bin: mee_bin, cos_bin, mee_lo,
  mee_hi, cos_lo, cos_hi, weight).  It also makes the weight-map plot.
- ``apply_pi0_dalitz_reweighting`` reads that grid and, for every truth pi0 Dalitz
  decay in the df, finds the (m_ee, cos theta*) bin the event falls in and applies
  its weight -- adding a standalone ``pi0_dalitz_reweight_weight`` column (1.0 for
  non-Dalitz events) and multiplying it into ``wc_net_weight``.  It also rebuilds the
  full closure / lab-frame monitoring plots (overlaying the real BNB Dalitz events on
  the Geant4/EvtGen reference curves).

The per-event ``(m_ee, cos theta*)`` are computed once, for every truth pi0 Dalitz
decay (including the partially-saved ones, with missing-lepton recovery), in
``do_wc_postprocessing`` (postprocessing.py), and stored as the scalar df columns
``wc_true_pi0_dalitz_m_ee`` / ``wc_true_pi0_dalitz_cos_theta_star`` (plus the
gamma/e+/e- lab four-vectors, used only to rebuild the monitoring plots and then
dropped by apply).  apply does a straight per-row bin lookup on those columns, so
there is no join (and hence no issue with run/subrun/event colliding across the
derived overlay copies): each row is weighted from its own truth invariants.
"""

import os
from datetime import datetime

import numpy as np
import pandas as pd
import polars as pl
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from file_locations import data_files_location, intermediate_files_location, other_files_location

# plots/ folder lives at the repo root (parent of this src/ directory)
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_PLOT_DIR = os.path.join(_REPO_ROOT, "plots", "pi0_dalitz")

# ── Physical constants (MeV) ─────────────────────────────────────────────────
M_PI0 = 134.9768
M_E = 0.51099895

# ── High-stats pure-model samples (1M each), source and target of the weight ──
# Standalone Geant4 (G4DalitzDecayChannel, isotropic) and EvtGen (PI0_DALITZ, QED).
# Generated by geant4/build_and_run.sh and evtgen/build_and_run.sh respectively.
GEANT4_CSV = os.path.join(other_files_location, "geant4_pi0_dalitz.csv")
EVTGEN_CSV = os.path.join(other_files_location, "evtgen_pi0_dalitz.csv")

# ── Reweighting binning (notebook cell 68451bc6) ─────────────────────────────
NM, NC = 25, 20  # m_ee bins (quantile-spaced), cos(theta*) bins (uniform)

# df columns produced by do_wc_postprocessing for every truth pi0 Dalitz decay
_MEE_COL = "wc_true_pi0_dalitz_m_ee"
_COS_COL = "wc_true_pi0_dalitz_cos_theta_star"
# (recovered) gamma / e+ / e- lab four-vector columns, stored only to rebuild the
# monitoring plots; apply_pi0_dalitz_reweighting drops them right after plotting.
_LAB_P4_COLS = [f"wc_true_pi0_dalitz_{name}_{c}"
                for name in ("gamma", "ep", "em") for c in ("E", "px", "py", "pz")]


# ── Four-vector helpers ([E, px, py, pz]) ────────────────────────────────────
# get_dalitz_rest_frame_observables() is also imported by postprocessing.py to fill
# the m_ee / cos theta* columns from the recovered gamma/e+/e- four-vectors.
def boost_to_rest(p4, frame_p4):
    p4 = np.asarray(p4, dtype=float)
    frame_p4 = np.asarray(frame_p4, dtype=float)
    E_frame = frame_p4[..., 0]
    beta = frame_p4[..., 1:] / E_frame[..., None]
    b2 = np.sum(beta**2, axis=-1)
    gamma = 1.0 / np.sqrt(1.0 - b2)
    pe = p4[..., 0]
    pv = p4[..., 1:]
    bp = np.sum(beta * pv, axis=-1)
    with np.errstate(divide="ignore", invalid="ignore"):
        gamma2 = np.where(b2 > 0, (gamma - 1.0) / b2, 0.0)
    E_prime = gamma * (pe - bp)
    pv_prime = pv + (gamma2 * bp - gamma * pe)[..., None] * beta
    return np.concatenate([E_prime[..., None], pv_prime], axis=-1)


def p3(p4):
    return p4[..., 1:]


def minkowski_mass(p4):
    return np.sqrt(np.clip(p4[..., 0]**2 - np.sum(p4[..., 1:]**2, axis=-1), 0, None))


def cos_between(a3, b3):
    c = np.sum(a3 * b3, axis=-1) / (np.linalg.norm(a3, axis=-1) * np.linalg.norm(b3, axis=-1))
    return np.clip(c, -1.0, 1.0)


def get_dalitz_rest_frame_observables(gamma, ep, em):
    """All pi0-rest-frame Dalitz observables from (N, 4) lab four-vectors."""
    pi0 = gamma + ep + em
    g = boost_to_rest(gamma, pi0)
    p = boost_to_rest(ep, pi0)
    m = boost_to_rest(em, pi0)
    ee = p + m
    ep_in_ee = boost_to_rest(p, ee)
    return {
        "E_gamma": g[:, 0], "E_ep": p[:, 0], "E_em": m[:, 0],
        "m_ee": minkowski_mass(ee),
        "opening": np.degrees(np.arccos(cos_between(p3(p), p3(m)))),
        "asym": (p[:, 0] - m[:, 0]) / (p[:, 0] + m[:, 0]),
        "cos_theta_l": cos_between(p3(ep_in_ee), p3(ee)),
    }


def load_daughters(path):
    """Load gamma / e+ / e- lab four-vectors ([E, px, py, pz]) from a CSV sample."""
    d = pd.read_csv(path)
    return (d[["E_g", "px_g", "py_g", "pz_g"]].values,
            d[["E_ep", "px_ep", "py_ep", "pz_ep"]].values,
            d[["E_em", "px_em", "py_em", "pz_em"]].values)


def _build_weight_grid():
    """Build w(m_ee, cos theta*) = EvtGen / Geant4 from the 1M pure-model CSVs.

    Returns (g4_obs, ev_obs, mee_edges, cos_edges, W2, weight_of)."""
    g4_obs = get_dalitz_rest_frame_observables(*load_daughters(GEANT4_CSV))
    ev_obs = get_dalitz_rest_frame_observables(*load_daughters(EVTGEN_CSV))

    mee_edges = np.quantile(g4_obs["m_ee"], np.linspace(0, 1, NM + 1))
    mee_edges[0], mee_edges[-1] = 2 * M_E, M_PI0
    cos_edges = np.linspace(-1, 1, NC + 1)

    Hg, _, _ = np.histogram2d(g4_obs["m_ee"], g4_obs["cos_theta_l"], bins=[mee_edges, cos_edges])
    He, _, _ = np.histogram2d(ev_obs["m_ee"], ev_obs["cos_theta_l"], bins=[mee_edges, cos_edges])
    fg, fe = Hg / Hg.sum(), He / He.sum()
    W2 = np.divide(fe, fg, out=np.zeros_like(fe), where=fg > 0)

    def weight_of(mee, cos):
        i = np.clip(np.digitize(mee, mee_edges) - 1, 0, NM - 1)
        j = np.clip(np.digitize(cos, cos_edges) - 1, 0, NC - 1)
        return W2[i, j]

    return g4_obs, ev_obs, mee_edges, cos_edges, Hg, W2, weight_of


def compute_pi0_dalitz_reweighting(make_plots=True):
    """Compute and save the pi0 Dalitz Geant4->EvtGen bin-by-bin weight grid.

    Uses *only* the 1M standalone-Geant4 (source) and 1M EvtGen (target) CSV
    samples to build the 2D weight ``w(m_ee, cos theta*) = EvtGen / Geant4`` (a
    density ratio, so <w> = 1 over the Geant4 model by construction).  Writes the
    grid -- one row per bin -- to ``pi0_dalitz_reweighting.parquet`` in
    ``intermediate_files_location`` and (if ``make_plots``) the weight-map plot to
    ``plots/pi0_dalitz/``.  apply_pi0_dalitz_reweighting then looks up the per-event
    weight from this grid (and rebuilds the closure / lab-frame plots).
    """
    print("computing pi0 Dalitz Geant4->EvtGen reweighting grid")
    os.makedirs(_PLOT_DIR, exist_ok=True)

    g4_obs, ev_obs, mee_edges, cos_edges, Hg, W2, weight_of = _build_weight_grid()
    # Geant4 closure weights (mean ~1 over the Geant4 model by construction)
    w = weight_of(g4_obs["m_ee"], g4_obs["cos_theta_l"])
    n_eff = w.sum()**2 / np.sum(w**2)
    populated = W2[Hg > 0]
    print(f"  source (standalone Geant4): {len(g4_obs['m_ee']):,}")
    print(f"  target (EvtGen):            {len(ev_obs['m_ee']):,}")
    print(f"  grid: {NM} m_ee bins x {NC} cos(theta*) bins, min Geant4/bin = {int(Hg.min())}")
    print(f"  weight range: {populated.min():.2f} .. {populated.max():.2f}")
    print(f"  Kish effective N (source): {n_eff:.0f} / {len(w)}  ({n_eff/len(w)*100:.0f}%)")

    if make_plots:
        _plot_weight_map(W2, Hg, cos_edges, w, n_eff)

    # ── Save the bin-by-bin grid (one row per (m_ee bin, cos theta* bin)) ──────
    ii, jj = np.meshgrid(np.arange(NM), np.arange(NC), indexing="ij")
    grid = pl.DataFrame({
        "mee_bin": ii.ravel(),
        "cos_bin": jj.ravel(),
        "mee_lo": np.repeat(mee_edges[:-1], NC),
        "mee_hi": np.repeat(mee_edges[1:], NC),
        "cos_lo": np.tile(cos_edges[:-1], NM),
        "cos_hi": np.tile(cos_edges[1:], NM),
        "weight": W2.ravel(),
    })
    out_path = f"{intermediate_files_location}/pi0_dalitz_reweighting.parquet"
    grid.write_parquet(out_path)
    print(f"  saved {out_path}  ({grid.height} bins)")

    # ── Write a log of this run into the plot directory ───────────────────────
    now = datetime.now()
    log_lines = [
        "pi0 Dalitz Geant4->EvtGen reweighting log",
        "=========================================",
        f"created: {now.strftime('%Y-%m-%d %H:%M:%S')} ({now.astimezone().tzname()})",
        "replicates: ipynb_notebooks/pi0_dalitz_reweighting.ipynb",
        "reference: https://doi.org/10.1103/PhysRevC.95.025202",
        "",
        "weight grid (source -> target, pure-model 1M samples):",
        f"  source (standalone Geant4): {GEANT4_CSV}  ({len(g4_obs['m_ee']):,} decays)",
        f"  target (EvtGen):            {EVTGEN_CSV}  ({len(ev_obs['m_ee']):,} decays)",
        f"  binning: NM={NM} quantile m_ee bins x NC={NC} uniform cos(theta*) bins",
        f"  min Geant4 events / bin: {int(Hg.min())}",
        f"  weight range: {populated.min():.3f} .. {populated.max():.3f} "
        "(EvtGen/Geant4 density ratio, <w>=1 over Geant4)",
        f"  Kish effective N (source): {n_eff:.0f} / {len(w)} ({n_eff/len(w)*100:.0f}%)",
        "",
        "outputs:",
        f"  grid parquet: {out_path}  ({grid.height} bins)",
        "  columns: mee_bin, cos_bin, mee_lo, mee_hi, cos_lo, cos_hi, weight",
        f"  make_plots: {make_plots} (plots in this directory)",
    ]
    log_path = os.path.join(_PLOT_DIR, "reweighting_log.txt")
    with open(log_path, "w") as fh:
        fh.write("\n".join(log_lines) + "\n")
    print(f"  wrote log {log_path}")

    return grid


def _load_weight_grid():
    """Read pi0_dalitz_reweighting.parquet back into (mee_edges, cos_edges, W2)."""
    grid = pl.read_parquet(
        f"{intermediate_files_location}/pi0_dalitz_reweighting.parquet"
    ).sort(["mee_bin", "cos_bin"])
    n_mee = int(grid["mee_bin"].max()) + 1
    n_cos = int(grid["cos_bin"].max()) + 1
    W2 = grid["weight"].to_numpy().reshape(n_mee, n_cos)
    mee_lo = grid.filter(pl.col("cos_bin") == 0).sort("mee_bin")
    cos_lo = grid.filter(pl.col("mee_bin") == 0).sort("cos_bin")
    mee_edges = np.append(mee_lo["mee_lo"].to_numpy(), mee_lo["mee_hi"].to_numpy()[-1])
    cos_edges = np.append(cos_lo["cos_lo"].to_numpy(), cos_lo["cos_hi"].to_numpy()[-1])
    return mee_edges, cos_edges, W2


def apply_pi0_dalitz_reweighting(df, make_plots=True):
    """Apply the pi0 Dalitz Geant4->EvtGen reweighting to existing events in-place.

    Reads the bin-by-bin weight grid written by compute_pi0_dalitz_reweighting and,
    for every truth pi0 Dalitz decay in the df, finds the (m_ee, cos theta*) bin the
    event falls in (from the precomputed ``wc_true_pi0_dalitz_m_ee`` /
    ``wc_true_pi0_dalitz_cos_theta_star`` columns) and applies that bin's weight.

    Unlike the rad-corr / coherent-1g reweightings (which APPEND new derived rows),
    this is a pure shape correction to events already in the df, so it adds no rows.
    It adds a standalone ``pi0_dalitz_reweight_weight`` column (1.0 for non-Dalitz
    events).  The caller is responsible for folding that factor into each per-config
    net-weight column (create_df multiplies it into every wc_net_weight_* column),
    since there is no single canonical net-weight column anymore.
    The lookup is per-row from each event's own truth invariants -- no join -- so
    run/subrun/event colliding across the derived overlay copies is a non-issue.

    If ``make_plots``, it also rebuilds the full notebook monitoring-plot set
    (closure_key, closure_mee_scales, closure_other, lab_frame -- overlaying the real
    BNB Dalitz events, raw and reweighted, on the Geant4/EvtGen reference curves) from
    the stored gamma/e+/e- lab four-vector columns, then DROPS those columns so they
    do not bloat the returned df.
    """
    print("applying pi0 Dalitz Geant4->EvtGen reweighting to the dataframe")

    # The per-event bin lookup is a numpy digitize, so we need an eager frame.
    if isinstance(df, pl.LazyFrame):
        df = df.collect()

    mee_edges, cos_edges, W2 = _load_weight_grid()
    n_mee, n_cos = W2.shape

    def weight_of(mee, cos):
        i = np.clip(np.digitize(mee, mee_edges) - 1, 0, n_mee - 1)
        j = np.clip(np.digitize(cos, cos_edges) - 1, 0, n_cos - 1)
        return W2[i, j]

    mee = df[_MEE_COL].to_numpy()
    cos = df[_COS_COL].to_numpy()
    is_dalitz = df["wc_true_has_pi0_dalitz_decay"].to_numpy() & (mee > 0)
    weight = np.where(is_dalitz, weight_of(mee, cos), 1.0)
    print(f"  weighted {int(is_dalitz.sum()):,} Dalitz events "
          f"(weight range {weight[is_dalitz].min():.3f} .. {weight[is_dalitz].max():.3f})"
          if is_dalitz.any() else "  no Dalitz events to weight")

    if make_plots and is_dalitz.any():
        _plot_application(df, is_dalitz, weight_of, mee_edges, cos_edges)

    # add the standalone per-event factor; the caller folds it into each
    # per-config net-weight column (there is no single canonical wc_net_weight).
    df = df.with_columns(
        pl.Series("pi0_dalitz_reweight_weight", weight).cast(pl.Float32)
    )

    # Drop the transient lab four-vector columns now that the plots are made.
    stale = [c for c in _LAB_P4_COLS if c in df.columns]
    if stale:
        df = df.drop(stale)
    return df


def _plot_application(df, is_dalitz, weight_of, mee_edges, cos_edges):
    """Rebuild the overlay/lab monitoring plots from the stored Dalitz columns.

    Overlays the real BNB Dalitz events (raw + reweighted) on the Geant4 (source) and
    EvtGen (target) reference curves, reproducing the notebook's closure_key,
    closure_mee_scales, closure_other and lab_frame plots."""
    # overlay Dalitz events: rebuild gamma/e+/e- lab four-vectors from the columns
    ov = df.filter(pl.Series(is_dalitz))
    def p4(name):
        return ov.select([f"wc_true_pi0_dalitz_{name}_{c}" for c in ("E", "px", "py", "pz")]).to_numpy()
    ov_gamma, ov_ep, ov_em = p4("gamma"), p4("ep"), p4("em")
    ov_obs = get_dalitz_rest_frame_observables(ov_gamma, ov_ep, ov_em)
    w_ov = weight_of(ov_obs["m_ee"], ov_obs["cos_theta_l"])

    # Geant4 (source) and EvtGen (target) reference samples + Geant4 closure weights
    g4_obs = get_dalitz_rest_frame_observables(*load_daughters(GEANT4_CSV))
    ev_obs = get_dalitz_rest_frame_observables(*load_daughters(EVTGEN_CSV))
    w_g4 = weight_of(g4_obs["m_ee"], g4_obs["cos_theta_l"])

    _plot_closures(g4_obs, ev_obs, ov_obs, w_g4, w_ov, mee_edges, cos_edges)
    _plot_lab_frame(ov_gamma, ov_ep, ov_em, w_ov)


def _savefig(name):
    plt.savefig(os.path.join(_PLOT_DIR, name + ".pdf"))
    plt.savefig(os.path.join(_PLOT_DIR, name + ".png"), dpi=200)


def _plot_weight_map(W2, Hg, cos_edges, w, n_eff):
    """Weight map and per-event weight distribution (notebook cell 837d388b)."""
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    Wm = np.ma.masked_where(Hg == 0, W2)
    im = axes[0].pcolormesh(np.arange(NM + 1), cos_edges, Wm.T, cmap="RdBu_r", vmin=0, vmax=2)
    axes[0].set_xlabel(r"$m_{ee}$ quantile-bin index (low $\to$ high mass)")
    axes[0].set_ylabel(r"$\cos\theta^{*}$")
    axes[0].set_title(r"weight $w(m_{ee}, \cos\theta^{*})$ = EvtGen / Geant4")
    fig.colorbar(im, ax=axes[0], label="weight")
    axes[1].hist(w, bins=50, histtype="step", color="tab:green")
    axes[1].axvline(1.0, ls=":", color="gray")
    axes[1].set_xlabel("per-event weight")
    axes[1].set_ylabel("Geant4 decays")
    axes[1].set_title(f"weights ($N_{{eff}}$ = {n_eff:.0f} / {len(w)})")
    fig.tight_layout()
    _savefig("reweight_weight_map")
    plt.close(fig)


def _closure(ax, key, bins, xlabel, g4_obs, ev_obs, ov_obs, w_g4, w_ov, logx=False, logy=False):
    """Full closure for one variable: Geant4 (source) reweighted (green dashed) lands
    on EvtGen (target, red) by construction, and the real BNB overlay Dalitz events
    (purple) reweighted (orange dashed) should also land on EvtGen."""
    ax.hist(g4_obs[key], bins=bins, density=True, histtype="step", lw=1.4,
            color="tab:blue", alpha=0.7, label="Geant4 (new generation)")
    ax.hist(ov_obs[key], bins=bins, density=True, histtype="step", lw=1.4,
            color="tab:purple", label=r"BNB overlay Dalitz")
    ax.hist(ev_obs[key], bins=bins, density=True, histtype="step", lw=1.6,
            color="tab:red", label="EvtGen (target)")
    ax.hist(g4_obs[key], bins=bins, density=True, weights=w_g4, histtype="step", lw=1.8,
            ls="--", color="tab:green", label="Geant4 reweighted")
    ax.hist(ov_obs[key], bins=bins, density=True, weights=w_ov, histtype="step", lw=1.8,
            ls="--", color="tab:orange", label=r"BNB overlay Dalitz reweighted")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("normalized")
    if logx:
        ax.set_xscale("log")
    if logy:
        ax.set_yscale("log")
    ax.legend(fontsize=7)


def _plot_closures(g4_obs, ev_obs, ov_obs, w_g4, w_ov, mee_edges, cos_edges):
    """closure_key, closure_mee_scales and closure_other (notebook cells 0b225747,
    1a884484, 8d01adf0)."""
    a = (g4_obs, ev_obs, ov_obs, w_g4, w_ov)

    # cos theta* and m_ee (the two reweighting variables)
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    _closure(axes[0], "cos_theta_l", cos_edges, r"$\cos\theta^{*}$", *a)
    xx = np.linspace(-1, 1, 200)
    axes[0].plot(xx, 3.0 / 8.0 * (1.0 + xx**2), "k:", lw=1.5, label=r"$1+\cos^2\theta^{*}$")
    axes[0].legend(fontsize=7)
    _closure(axes[1], "m_ee", mee_edges, r"$m_{ee}$ [MeV]", *a, logx=True, logy=True)
    fig.suptitle(r"$\pi^0$ Rest Frame")
    fig.tight_layout()
    _savefig("reweight_closure_key")
    plt.close(fig)

    # m_ee on linear and log-linear scales
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    _closure(axes[0], "m_ee", mee_edges, r"$m_{ee}$ [MeV]", *a)
    axes[0].set_title("linear-linear")
    _closure(axes[1], "m_ee", mee_edges, r"$m_{ee}$ [MeV]", *a, logx=True)
    axes[1].set_title("log-linear")
    fig.suptitle(r"$\pi^0$ Rest Frame")
    fig.tight_layout()
    _savefig("reweight_closure_mee_scales")
    plt.close(fig)

    # other pi0-rest-frame observables (functions of m_ee, cos theta*)
    fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
    _closure(axes[0], "asym", np.linspace(-1, 1, 60),
             r"energy asymmetry $(E^{*}_{e^+}-E^{*}_{e^-})/(E^{*}_{e^+}+E^{*}_{e^-})$", *a)
    _closure(axes[1], "E_ep", np.linspace(0, 68, 60), r"$E^{*}_{e^+}$ [MeV]", *a)
    _closure(axes[2], "E_gamma", np.linspace(0, 68, 60), r"$E^{*}_{\gamma}$ [MeV]", *a)
    fig.suptitle(r"$\pi^0$ Rest Frame")
    fig.tight_layout()
    _savefig("reweight_closure_other")
    plt.close(fig)


def _plot_lab_frame(gamma, ep, em, w_ov):
    """Lab-frame overlay raw vs reweighted (notebook cell 6ec4fc46)."""
    lab_E_gamma = gamma[:, 0]
    lab_E_ep = ep[:, 0]
    lab_opening = np.degrees(np.arccos(cos_between(p3(ep), p3(em))))
    lab_asym = (ep[:, 0] - em[:, 0]) / (ep[:, 0] + em[:, 0])
    lab_ee_gamma_angle = np.degrees(np.arccos(cos_between(p3(ep) + p3(em), p3(gamma))))

    def raw_vs_rw(ax, var, bins, xlabel):
        ax.hist(var, bins=bins, density=True, histtype="step", lw=1.4,
                color="tab:blue", alpha=0.6, label=r"BNB overlay Dalitz")
        ax.hist(var, bins=bins, density=True, weights=w_ov, histtype="step", lw=2.2,
                color="tab:green", label=r"BNB overlay Dalitz reweighted")
        ax.set_xlabel(xlabel)
        ax.set_ylabel("normalized")
        ax.legend(fontsize=8)

    fig, axes = plt.subplots(2, 3, figsize=(16, 9))
    raw_vs_rw(axes[0, 0], lab_E_gamma, np.linspace(0, np.percentile(lab_E_gamma, 99), 50),
              r"$E_{\gamma}$ [MeV]")
    raw_vs_rw(axes[0, 1], lab_E_ep, np.linspace(0, np.percentile(lab_E_ep, 99), 50),
              r"$E_{e^+}$ [MeV]")
    raw_vs_rw(axes[0, 2], lab_opening, np.linspace(0, np.percentile(lab_opening, 99), 50),
              r"$e^+e^-$ opening angle [deg]")
    raw_vs_rw(axes[1, 0], lab_asym, np.linspace(-1, 1, 50),
              r"$e^+e^-$ energy asymmetry $(E_{e^+}-E_{e^-})/(E_{e^+}+E_{e^-})$")
    raw_vs_rw(axes[1, 1], lab_ee_gamma_angle,
              np.linspace(0, np.percentile(lab_ee_gamma_angle, 99), 50),
              r"$e^+e^-$ momentum vs $\gamma$ opening angle [deg]")
    axes[1, 2].axis("off")
    fig.suptitle(r"Lab Frame")
    fig.tight_layout()
    _savefig("reweight_lab_frame")
    plt.close(fig)
